credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "derekpedersen github personal access token"
          id: "github_pat"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwDphlkiQTGtHk8Qrv129Hnxft50CT0Y1KcHqBfqse5Nomvc+vd1erMOgJvZi9zwKgU/PJNAZFp22LSzY1ULXxXQ==}"
      - usernamePassword:
          description: "derekpedersen username/password with pat"
          id: "derekpedersen_github"
          password: "{AQAAABAAAAAw4opxgx4aGIuF5K+e/MRnbnHErju0WFj4K+ZJ5mVy894EGgU34ZOT1vB1uLuNqEinSqVitzMfqfHoH75E9vUXSg==}"
          scope: GLOBAL
          username: "derekpedersen"
      - usernamePassword:
          description: "derekpedersen docker username/password"
          id: "derekpedersen_docker"
          password: "{AQAAABAAAAAQ7IkW/1HPt9qZoKGKDtILtLQitnvMM4CoZYxxhW76QHM=}"
          scope: GLOBAL
          username: "derekpedersen"
      - string:
          description: "gcloud project id"
          id: "GCLOUD_PROJECT_ID"
          scope: GLOBAL
          secret: "{AQAAABAAAABAm1zE2ekfR2OPY+e0I2ZAYfsUyvkJNsq9VrjLJ1/58EseLFVkqlajSpUJsQs2qkz54pm7GDfANpF764xr7Z9nqH83mC08nZjM1K4quvYA7AE=}"
      - string:
          description: "Odin gke service account json text"
          id: "odin_service_account_json_text"
          scope: GLOBAL
          secret: "{AQAAABAAAAwwgckl9xAS30IRc85pwudlJ4ZUnWI+LNBeXgje5k60FuIBU3TgUPMYCd4E2znwvBOlHRy505lIa9vT+qcnJ2cUKUTpDpwzyCOivbKhVVUF6Z1A9u+MlKti7NgyuU1O8laJnLZH2t2x06Cyfqpx2onlX/aoTcXbRkV3tkSNsI4o5NFxgp697e8jAOAF/ZHWzPseERdmyAzV6oE9ib29nMVC/4WFrokxcFu7tdDTLIYRybkfW7fjR+jOtEuXhil8JGpwqBIYdfsfMFt23iRnT6DLjXbrBng126wr3TVpJgQN0OqAjdikSVF+vkHmHoyeezNBb2m3T+ZBzNfLGdBBWsWWSyS/7pLxxNhv1UZAohHiGtQ9EUZxbXMimHtXc1y36leEE3RyfL9JrwUNngBojnj7t8GCRWtGl/O3fHWLHEFe0jKAFJoRRZ4AEmRwEmBTNW4vhUP5+4uKCinEMvbY2YYL5ujiJqzEr43LkLcGfCMPTjO0JkgplZz/kVZVDax3jEViWaDcmSJaowIGJkWdHNsbIR3mxvtslkK6rUVbDVhXjTGOPC7StwtYSOW98zjLbtpuYpWFafSy/um5/yPiafIk0VDab6ZJrdhGinEyVlKMgkXEf/eFVJwlb+BimE/e7AeLLNJNrqxSMufe87nXDGMEu9nZA8r5epikRKNk0eFbLcZ8rRcifCyQ7Gnu8Zca7S/WbeGvF6YUWFULMN5h8D0E+T2gCksYLbLcjhnt0drJmSPwQO/JuRhHT4hO7Iq0S8h7Nwzb8Qv1DSLDNyDO7VGwKAQ9oEsJ9S/pVyHiCpc0ZjuMYEywDyRQonzb2isnlZ4RlLAEKsdDt9s3bzSfyzq5r2UjLEUBCNYodjrzwah15MiaGz03N0y777HKGptCwFsqe93buq8gujdOHW072tTTzvwU4TvBOQ0IcpIbU9eDD6869p3GGB+bmeC0Wj11EOUJMhrs14kqqzhWT0y6erirrJToCgpdEo+dgCPzl7q9y15o4yJ1nEyidJt4B7VKCesiHknCNeYbOjfcEIPhn9qpxLgWJqxQxTBBEa3PN3xlHdeYlq64yFYWyNsswLY/yUWgnnmhWW/HhWgOGgjwrO7rIGLMZDZ+NxGqFxfPUfH/iEyfui743epq5ft7NtEB1r8BxXBPoOSvMIgY5uIsyGbmmD3c7l8FCR/a4nhF7iSZ1cs4sDuA8CuZP4xMWSH1yGrYAF3exOZnuCSDpuA4abK1Gb5WJbh9zRPDxuvhaCRf/lzd9MWoeOMiuMapui91LWbGe5PdC5FMadIKrftetuHxvpCt3hzHUsCPI9TPQhn/k6ChY3OJk4AiWajGp8gGMUufR7JOu3yWTY9Rrws7TNeUMbqPDEzsidTQMS1ms12E1T25tltyVxHqZGlhEDBM2wevSOQpYP4FWSZHw8ixyqncI/K38u4ZThJghJsWNnWdYQWpHb9gxZxh5ozrZpd+bxqg6A0FS/CzhxaD+lNlmsQVDYT30UqZgiVFEvne2bb2mQq+xMSoH+lsfCOuWdrC3taZrUPcShbsn7ZfuAD1QA7nwhqMJCVJcG1yBVRqIGBGwCfTH/ooiQIfloJeuB7dqZujCs4QBHeBcuy4/meRWkaH21h/4AGoZozeG9TGnir8dgrBQu5O0609rqHr9lRFh6ZlGBS96ZNcX804Von2J4fvr9DBqTAiZdsDW6FE9ECSpx8p65Xg27GdwGDl2dyk32v0AhRbbUE8JnIKACVi2hPUzX9RP8siM701PFy52+jFX44n0g/PoD6/vVEhpqp68pG/+m9fW1KXIU1A+2iQeEX7uzyCE0t219tM2fGEXuHYE9meMHn1GXP0WQCRgxEie5yPgbDxACa/NQHSX7K+APGD0uymnrY3Nm1ofNTDbOldH9VlY3Vj7U6oLbiPr3doLcZKGze3p3oIozpm2vkN1fvNxmOFY2bj7gcFIQZaEEd0Bwk8Wo/HuNRM5/Blss1UTVYrGj4pJMOcuJpqbith09iIDZjfKgeYE7RSjBC9/Zq3/LEM2W/76XCqUIknnXtpF2Zmt3ivtwKNT5w6lxNkqtnDUxpRL+Ok9RzfdZt8lRPyHu/PZue8pp5Jwqd7bHv/b6HrzVvN4UW9ruVcpxl8EMRi4Q9sfoycjJmZLJuD4edZT+IzHTZEznI4i8gzIOpUt8uYpqgH202W2VmRRXZJnzmJSmrYPwm0mC9QxGlkPeJxO2zAgj7ZyAIdGdMf/tos4Em0fcX7nUewIv7SjFAaQvXlGxCnx8l+i1ZZxNoqcPw9PhuJGg40mQbMI0BCHXSuZo7gXRdqcg6AHylGPCMylVRAsnvOJp12948RjD6HSaWMe5jvLOjRXx57jsJs5hEUcXS/cXcjcN/ldAL5syPYZ7X4qVHwXXW9XkQ8hzaHkzQ8feltbVgqGxfJejQ8b/PvVU/Dq1DJd6HO7x2ptgv8HAlOgjZzQ2oPHoBHUa/73L/7hImcbZ/cQcNZwoSqFKgVx3iIVYX0wyMXE6CVzGGfAOMww8itwJ360WlkVyMwySTAneGTuFIvecsMJTdTxfmH/sQF4Pa23XaOeU7uaESH7FfOoajENppuYWaz/2lpBrrop+oXe9kZN3Jz02/hnK3bjNH5CrgoRfyM/ATTYP3OKxFwWTYzvoEpRxvlzAzJDpToGemP9baHGFmqAQbvr1RcxxR5TuVRhXiTHFjVaEd8XnBiOi/g2Bnj4bZWKaAZFG3ydqsLA3vn2CJqhRikdZ1m/89Rb3TKDZjCS4A24tMSYdOI6kHgDmmZjxyJMae70dZpi6SbsPV8pyipatCqRg9as7ks76ubV6Naq4B3Pc683KPThqQPnHFCQMt50iKqyIs6wHKTIa++oPnhzW5GS2Pmzkp1Mi7Ryg9ojfewTft3vVML5uAtPl1bz0MbWuFdLFzdITanzQcmZvJk3rJqkKN7OhBlrsb6T2Ja84qt3ikdR/ncRNLs1h47iA7bLJ76grTSDHSaE9snUybR7HbTEx0udKR6oVGdrns8oNvemZe1MWAUjRwrZCgfIA0k3KfU9RB80+Ix/6ebQab7/r88aJGBqekq0MV0Vf0WwR46vZHxL08ttSLs7MuM/DaKnDrwnZIl0MBBlroHkrkBDpzvtNFg5BRL9OIZwoZ0YchePi70ZDN1gCeOcQpgBIDdRUhuEOIlq0zoGOd4pAlrDNMenXYAxiu6sStGMfAKFGMFmKx1gCNT9vWytkQ2nhVOUOG2YWTYvvw4xT5zZp3NCrQOA2VuF1hdlX9btknfUvbCde6MxInuNyEnJeL56TfDB+K6pyv0WhH34mTrTyDPeK33L/1kZfh4q6DylNrrQKwLafKVdjd8bEaOvNDj0RcTr632lj5fIMSgccrt7xWyQ+2aj1wiZCLqMilafim90QB7rkVHigYlggZhWTFIRsWyBHY/f3FvbpkTCSWfUc2BSPEz8djJUmwL/mkrgiw0Kt+r+OUgAizR3H4OdSRWIooh5/EKSO/rhFvY+vqdt4Qzej8s1mGqyLLSgN6ZxDSI8g5SnrmaLlVi8ellwfKZGU6H5HRCvycGbxWA/bCQgVE6aOXpfVW9r6rZKwDK1rsyCPcLn+5HAUBjXoXkwBJ8blj7eRlhnn3Us8w7qXM5ACbbEWny7rVSLuk79dup8bQJTpDLWrWufX/q7Kq1Y65mTnY3605I5ZEkIzUtjDgd8VXB+NXUrBhjrtllLP83rKLzJOjlu/2UZJhpyJrGJthQNPNPHQzIxPt8RwYIbNXy5MjeeIgDCgaRudoxxsIajTSPtrfTU6QUbbxQ1+Vl5OFTg5HJFSZoKMEj6DGdMTQGiPTC8LIw2WHXzmbPA+35H86yvQ/FRCHsphyj5u0JN1QUMfbFdbWWx01cPWBsND+4BzxieejD5Rki3vd30o4p5NWDueTikEh8MFRm0gvsojv/GlaGjg8Jl/2WdqQFxuqoWvfoLNHuF/w4RGN04XbspkHvH0qzhQEV79LTyBIuz/+/HA3Z5eDECWuixx0TueaCsXG/foj+dpvF4xMWGeFyQYQk/548BxqQqtvbnSGxfB4+unNVa5vSHmPBOMso+6axDl3RU+KN2kuUQRaOA8yyNyoSz0DUrPYU4I9ZMMZ1U2mwAxhkp4f7QCJZ7ISQG2z77TSC2xdjwUhiu9f5PNSgYcpM01SZorP9Y2gQVA==}"
      - file:
          description: "odin service account json file"
          fileName: "sleipnir-a3be28a3cbc6.json"
          id: "odin_service_account_json_file"
          scope: GLOBAL
          secretBytes: "{oljK2a8xQ3cH1xGJqeg3GSO/eAfEHqRsNYpjOEkcTUXJpkrP94erqkrXne8t3MdPEnPMGNU/nNVLPBJFx/0chQdQW6cHSNHGt0A+aQKd3UdGyrQOsho3mpAF8rr0qMJr3ENysxo5UeQvVjaSNGHQ/VqAaR0U7UhUubvSgU85uNHBqu3JUUp3k39VApDl/eKVrMGQunCE6layANbZtkdq85DtgBFPAvBXTjNVGD001EM5k9myQ20fNc61Y6+bK71KLTme7vLb5uLCYVvTisBvpbBM6jCcKczI2mgPDdjUOVtSYROOafZolKvFuMHl8uQ0AJQ8T+OuQkfXvHO8rGQTcWRFcpxMUki3Fb0jtcsUh8aWJk7ch+MyEL0tQwERmkA7flSqDq13K8PIHr2g84runa/AxMpOtRKIRFXqvI/GeLLcDGYjou2hMZrkNLCTlwMdVrJzosi6IQePa9frTApXMq9M/W1DAVjtwfEmAfgZQ1jgnwojISE0hOSFmms6zjFIHeLyfOPlOOeGF68aWEY1Ctx+Z/MxVkNFBLu45FKO010WBU7syzCxgdihvOXrex5D5BbwdiCFRzI0GqEGUDGPkzhYe8MSy3ofpBXgWjiQH/l1e5r6CcKP2QAlo0xBlMvS+cHFrJg37Dvc+DEBCCNJ4Db2fPnWLnQAaQZDUF2fpQAOsP5PumwJ37otan5rHr95EsvVOIL/DnHfhozhxKuKx5xanOOzJlS4havRjzbvzWbWx4rfweukiDrshXNhZmjR1NP3O+pFzqAQJ6sWfT/0yRBt75fYpq+znUaLFmTl4z/Ut+TaLT+X/doKEQTS8jjzvE7wIM8q2aFDpifzasD6xB5TE5We5lBpAh+c5oGTLgD1aiYW6PDZDcVSdNvFdtkqq8uAL+6gPLH7phrqu3Il4uqfpGDESAobJOFck9i1Wl3FH2ptZa6Rn+npxyVhUZg0FF+lRw+FcX2aNW12bT7NrEcx73x2D303Y2okwV733eEXzsfityn2j/CMrLTJjMa2A9LZN4smIsCUU1743EJt3jw3eT+5a5QuKczLLI+hOxxj9P1qmLqr06zQXnPNj2uSo/j5Cmp/bjBA8bfI6WvIm+zjg9yPsA9+TEFJ1UCGjQYXNvQVaumjgEbeGCGJmO7XkixMUc2ziFWgHTsioSJzK4xDPbf44fmtHvwaI0xjFv/UM27RJRV/uIC+8P12wjHX/tZuyVPFJlCPy6sbjy5kADEmHBlNTliuGPUK597lm4GSd/d6078pc3xjlZ7EF7/SIexip3BF3T/GqUIPLBN4HI+icepZKg3BVjC2F+T9Z0yiL4oXkCZdONKTrMXNzCh/6JT6xngTrm5BReSVoxGZt0hsZTxv8qxAIs40iix1BKFJCNrZ2UOjyVz7rykiBZ5D1aw/XZNmeDqYtCAsYUccHh9jO3OZ6SiWAdQxJm26OEo8mXGiah6UMvOlLigXAEQ9+/IEvi1w44xAoR/TAwG7bSKctMhNEfKe7aDO8AgX2NOlO3pNWyw+xk+gSLlj/fuDlZIu5H40Bu4aZFN2m69Uc9/53M3+50GQn61G7FxnF75L0jwm2xYa8X0ufSq6lg6+qI21D+C6O1EpIY171CBD2PkKSe03MqeZAdUW16CLN6OQBXJL1/Hs0huNF7faxPeKtekhg76gRX/Pc6LrJZi49CQT2pKbGizOKSV/MaqS5glbOwEJWRSvnNsmnmwjg08NGLA+Lpxd/1us0q38NGw4gmaTz4WcwqYjn3dfytUDAkFqFwhFVsiHUWcbkKFv5QZRLrro20xVu1z0GxGHJ+kUw/7jICzd7dvKj2qr9FDxpGdlEMGsXh4RY4nyUHhwGJahyEaD4Z4eKthTtTzOSBLp4AZzrjfE347vVqO5idt5LskVi55LE+wo6YW/FUoi6OtuJZ77pcTxjnISNtZdtjVkTrOHWGcdLGnbIquiafz9LzFb3iIeQeH4ZbG0I2B/EFUyfYFg2lfeQ7NDsN33sZmBTpjHLdorHt6FvX3pXDCrmtBb8DOQKs7q60Ts1dqctqXOObdKUTziwrMLyo2oqPzEwNh2+cR1i3gHIsTz48CmFtxMBTk3UswQqcTiD1l+8cKH+fRyYAo7hQ2e8UOP/9Uh5r12vdxHvffnJhSyruZTHaM9X945Z4wPff1Dzm078lbRXIktI3k4N0gdCe5eQS53oj4rs8h6A6sqodin3SZZ5dIWz5qnm43z5kFl2x1Q8PPrNkCbyG8JYh9ilT+5GCPwwFhk25BkTEf4eH4X3mUN7GdQBSqhIhEHmXK09Z4ho0xlsaxmL9LNEcZaWuRUKxKJlh1ByAuNiQ1NgF/QjxcpiwoewTn7ZlFsmOK/9FZSAV1Iromav5iOBiIOgTRRNXZldwyUcKx0gkZ3g1omw1RzyEzhHVnF0rRTLDwAqTnmbsHy+fPGuTSfo68+z3lfAK8V+Su+1rkV76RBXnAF5aMtkUlFWWLfbI5nQev1zg8eucKG103z9OQqAkkd7HXSwtn9RMUiQPdBTVTy06pKL2VfcsOWu5Gm1GBIUQ7m2Z7zMy7rHmmrnues2htM5fXz7gr0XhyUkHGs1Fvc45RoNiXdgGEJPBw8lDSr3Vy/UEJDdd2SGEw/4oYIlO8BoZXOdecUZiBhvCB0KJaJ0NgYXIklTGw7hSkcDImcq1Od2AKIFQzxT+Z6VaSkEIiYod7VCVm2nPyuV5ZjCYWj/AASwONVBtHnRnlWDv/PR91IeAH8WYxkTqXKSco4k9KIyFJzUfXjd2d2pgyv5JMaHRTV8xR4Md/qkecA382r0AykGbC5djIow9pVJ6832JXu1lCzlNMHnbrpbMZjk/FaQeJ5MT6UDbkt/hwpHaaS39fOhB3WnUflKw+KiLRQ1zJTmnxmMV+/Brjgkn3fH19/ZhWpWWBUNR7B0f5b5lHqWjnWsdXDXo5xQy+aI/yFdGjmL/VEB/C30BIZZB2+eOAgDx+iVG3TF11DOzm0PsidmZhmKjJOX5i/rSTEQZNeG09uXzMc/mGlX12fzTz6JYr/KisWg9D9aWS2p6LDqf4QB1VooVgUUXRCr4Nc/DnVa5d0O3dmDWXtNNeqTvrtMva7BR/wwcyvpB1G6reZ8KTIkvkyeJ64ELkX}"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Agent/Build:derekpedersen"
      - "Agent/Configure:derekpedersen"
      - "Agent/Connect:derekpedersen"
      - "Agent/Create:derekpedersen"
      - "Agent/Delete:derekpedersen"
      - "Agent/Disconnect:derekpedersen"
      - "Credentials/Create:derekpedersen"
      - "Credentials/Delete:derekpedersen"
      - "Credentials/ManageDomains:derekpedersen"
      - "Credentials/Update:derekpedersen"
      - "Credentials/View:derekpedersen"
      - "Job/Build:derekpedersen"
      - "Job/Cancel:derekpedersen"
      - "Job/Configure:derekpedersen"
      - "Job/Create:derekpedersen"
      - "Job/Delete:derekpedersen"
      - "Job/Discover:derekpedersen"
      - "Job/Move:derekpedersen"
      - "Job/Read:derekpedersen"
      - "Job/Workspace:derekpedersen"
      - "Lockable Resources/Reserve:derekpedersen"
      - "Lockable Resources/Unlock:derekpedersen"
      - "Lockable Resources/View:derekpedersen"
      - "Metrics/HealthCheck:derekpedersen"
      - "Metrics/ThreadDump:derekpedersen"
      - "Metrics/View:derekpedersen"
      - "Overall/Administer:derekpedersen"
      - "Overall/Read:derekpedersen"
      - "Run/Delete:derekpedersen"
      - "Run/Replay:derekpedersen"
      - "Run/Update:derekpedersen"
      - "SCM/Tag:derekpedersen"
      - "View/Configure:derekpedersen"
      - "View/Create:derekpedersen"
      - "View/Delete:derekpedersen"
      - "View/Read:derekpedersen"
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-1619548353-agent.default.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins-1619548353.default.svc.cluster.local:8080"
      name: "kubernetes"
      namespace: "default"
      podLabels:
      - key: "jenkins/jenkins-1619548353-jenkins-agent"
        value: "true"
      serverUrl: "https://kubernetes.default"

      templates:
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          image: "us.gcr.io/sleipnir/build-golang:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          resourceLimitCpu: ".5"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: ".1"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins"
        id: "e4a18b6c-8e74-498c-adad-53d145c92728"
        idleMinutes: 15
        idleMinutesStr: "15"
        instanceCap: 5
        instanceCapStr: "5"
        label: "build-golang-stable"
        name: "golang"
        nodeUsageMode: "NORMAL"
        podRetention: "onFailure"
        serviceAccount: "default"
        slaveConnectTimeout: 600
        slaveConnectTimeoutStr: "600"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          image: "us.gcr.io/sleipnir/build-node:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          ttyEnabled: true
          workingDir: "/home/jenkins"
        id: "6170664b-ab08-46ae-a41d-a2721b714a12"
        idleMinutes: 15
        idleMinutesStr: "15"
        instanceCap: 5
        instanceCapStr: "5"
        label: "build-node-stable"
        name: "node"
        podRetention: "onFailure"
        slaveConnectTimeout: 600
        slaveConnectTimeoutStr: "600"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          image: "us.gcr.io/sleipnir/build-jenkins-base:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          ttyEnabled: true
          workingDir: "/home/jenkins/agent"
        id: "02b8986f-3c2b-46a9-9b2a-00ba2e83cc4e"
        idleMinutes: 15
        idleMinutesStr: "15"
        instanceCap: 5
        instanceCapStr: "5"
        label: "build-base-stable"
        name: "jenkins"
        podRetention: "onFailure"
        slaveConnectTimeout: 600
        slaveConnectTimeoutStr: "600"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins-1619548353.default.svc.cluster.local:8080/"
          image: "jenkins/inbound-agent:4.6-1"
          name: "jnlp"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins"
        id: "d591f91bc14f64a22ae985a40af25e183925bcf2934d14c02f9026358a3a047c"
        label: "jenkins-1619548353-jenkins-agent"
        name: "default"
        nodeUsageMode: NORMAL
        podRetention: "never"
        serviceAccount: "default"
        yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.security.QueueItemAuthenticatorMonitor"
  labelAtoms:
  - name: "jenkins-1619548353-jenkins-agent"
  - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    github:
      clientID: "725008ee2da8b3bd533e"
      clientSecret: "{AQAAABAAAAAwhHkLK2VcRC5TGHN1KLnEGetBgje5KFD9hXEe9/nmZQZKQMliAw5TLUBfVg5pzHrtpCxqFcIR81hB+7piECBlBg==}"
      githubApiUri: "https://api.github.com"
      githubWebUri: "https://github.com"
      oauthScopes: "read:org,user:email,repo"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  casCGlobalConfig:
    configurationPath: "https://raw.githubusercontent.com/pedersen-io/gke-jenkins/master/jenkins.yaml"
  defaultFolderConfiguration:
    healthMetrics:
    - worstChildHealthMetric:
        recursive: true
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    configs:
    - credentialsId: "github_pat"
      manageHooks: false
      name: "github.com"
    hookUrl: "https://jenkins.pedersen.io/github-webhook/"
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "github_pat"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      name: "github"
      readTimeout: 10
    useAuthenticatedEndpoint: false
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    globalConfigEmail: "jenkins@pedersen.io"
    globalConfigName: "jenkins"
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "jenkins@pedersen.io"
    url: "https://jenkins.pedersen.io/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"